version: '2'
services:
  back:
    container_name: test.back
    build: .
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./back:/app
    dns: 
      - '8.8.8.8'
      - '8.8.4.4'
    networks:
      - test-net

  test-db:
    container_name: test.db
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Test@3661
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: Test@3661
    volumes:
      - ./.db:/var/lib/mysql
    networks:
      - test-net
      
networks:
  test-net:
    external: true